# Generated by Django 6.0.3 on 2026-04-04 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SchoolClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "exam_type",
                    models.CharField(
                        choices=[
                            ("oge", "ОГЭ"),
                            ("ege_profile", "ЕГЭ профиль"),
                            ("ege_base", "ЕГЭ база"),
                        ],
                        max_length=20,
                        verbose_name="Тип экзамена",
                    ),
                ),
            ],
            options={
                "verbose_name": "Класс",
                "verbose_name_plural": "Классы",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Variant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Номер варианта"
                    ),
                ),
                (
                    "exam_type",
                    models.CharField(
                        choices=[
                            ("oge", "ОГЭ"),
                            ("ege_profile", "ЕГЭ профиль"),
                            ("ege_base", "ЕГЭ база"),
                        ],
                        max_length=20,
                        verbose_name="Тип экзамена",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
            ],
            options={
                "verbose_name": "Вариант",
                "verbose_name_plural": "Варианты",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255, verbose_name="ФИО")),
                (
                    "password_hash",
                    models.CharField(max_length=255, verbose_name="Пароль (хэш)"),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Ключ сессии",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "school_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="students",
                        to="exam.schoolclass",
                        verbose_name="Класс",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ученик",
                "verbose_name_plural": "Ученики",
                "ordering": ["school_class", "full_name"],
            },
        ),
        migrations.CreateModel(
            name="Attempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Начало"),
                ),
                (
                    "finished_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Конец"),
                ),
                (
                    "is_finished",
                    models.BooleanField(default=False, verbose_name="Завершена"),
                ),
                (
                    "score",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Первичный балл"
                    ),
                ),
                (
                    "max_score",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Максимальный балл"
                    ),
                ),
                (
                    "grade",
                    models.CharField(blank=True, max_length=20, verbose_name="Оценка"),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="exam.student",
                        verbose_name="Ученик",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="exam.variant",
                        verbose_name="Вариант",
                    ),
                ),
            ],
            options={
                "verbose_name": "Попытка",
                "verbose_name_plural": "Попытки",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField(verbose_name="Номер задания")),
                ("text", models.TextField(blank=True, verbose_name="Текст задания")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="tasks/",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "correct_answer",
                    models.CharField(max_length=255, verbose_name="Правильный ответ"),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("fipi", "ФИПИ"),
                            ("print_solve", "Распечатай и реши"),
                            ("dinamika", "Динамика"),
                            ("manual", "Вручную"),
                        ],
                        default="manual",
                        max_length=20,
                        verbose_name="Источник",
                    ),
                ),
                (
                    "points",
                    models.PositiveIntegerField(default=1, verbose_name="Баллы"),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="exam.variant",
                        verbose_name="Вариант",
                    ),
                ),
            ],
            options={
                "verbose_name": "Задание",
                "verbose_name_plural": "Задания",
                "ordering": ["variant", "number"],
                "unique_together": {("variant", "number")},
            },
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student_answer",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Ответ ученика"
                    ),
                ),
                (
                    "is_correct",
                    models.BooleanField(default=False, verbose_name="Правильно"),
                ),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="exam.attempt",
                        verbose_name="Попытка",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="exam.task",
                        verbose_name="Задание",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ответ",
                "verbose_name_plural": "Ответы",
                "unique_together": {("attempt", "task")},
            },
        ),
    ]
