# Generated by Django 6.0 on 2026-04-06 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="variant",
            name="max_attempts",
            field=models.PositiveIntegerField(
                default=3, help_text="0 = без ограничений", verbose_name="Макс. попыток"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="full_name",
            field=models.CharField(max_length=255, unique=True, verbose_name="ФИО"),
        ),
    ]
