# Generated by Django 6.0 on 2026-04-06 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0002_security_updates"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolclass",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активен"),
        ),
        migrations.AddField(
            model_name="task",
            name="topic",
            field=models.CharField(
                blank=True,
                choices=[
                    ("algebra", "Алгебра"),
                    ("geometry", "Геометрия"),
                    ("probability", "Вероятность и статистика"),
                    ("functions", "Функции"),
                    ("equations", "Уравнения и неравенства"),
                    ("number_theory", "Теория чисел"),
                    ("practical", "Практические задачи"),
                    ("other", "Другое"),
                ],
                default="other",
                max_length=30,
                verbose_name="Тема",
            ),
        ),
    ]
