# Generated by Django 6.0 on 2026-04-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0006_answer_student_answer_textfield"),
    ]

    operations = [
        migrations.CreateModel(
            name="CatalogTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_number",
                    models.IntegerField(
                        blank=True,
                        help_text="1–25, пусто = не определено",
                        null=True,
                        verbose_name="Номер задания",
                    ),
                ),
                (
                    "exam_type",
                    models.CharField(
                        choices=[
                            ("oge", "ОГЭ"),
                            ("ege_profile", "ЕГЭ профиль"),
                            ("ege_base", "ЕГЭ база"),
                        ],
                        max_length=20,
                        verbose_name="Тип экзамена",
                    ),
                ),
                ("text", models.TextField(blank=True, verbose_name="Текст задания")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="catalog/",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "correct_answer",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Правильный ответ"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("fipi", "ФИПИ"),
                            ("print_solve", "Распечатай и реши"),
                            ("dinamika", "Динамика"),
                            ("manual", "Вручную"),
                        ],
                        default="manual",
                        max_length=20,
                        verbose_name="Источник",
                    ),
                ),
                (
                    "topic",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("algebra", "Алгебра"),
                            ("geometry", "Геометрия"),
                            ("probability", "Вероятность и статистика"),
                            ("functions", "Функции"),
                            ("equations", "Уравнения и неравенства"),
                            ("number_theory", "Теория чисел"),
                            ("practical", "Практические задачи"),
                            ("other", "Другое"),
                        ],
                        default="other",
                        max_length=30,
                        verbose_name="Тема",
                    ),
                ),
                (
                    "points",
                    models.PositiveIntegerField(default=1, verbose_name="Баллы"),
                ),
                (
                    "manual_grading",
                    models.BooleanField(default=False, verbose_name="Ручная проверка"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "sdamgia_id",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        unique=True,
                        verbose_name="ID СдамГИА",
                    ),
                ),
            ],
            options={
                "verbose_name": "Задание каталога",
                "verbose_name_plural": "Задания каталога",
                "ordering": ["task_number", "-created_at"],
            },
        ),
    ]
