# Generated by Django 6.0 on 2026-04-09 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0007_catalog_task"),
    ]

    operations = [
        migrations.CreateModel(
            name="CatalogImportSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("fipi", "ФИПИ"),
                            ("sdamgia", "СдамГИА"),
                            ("manual", "Вручную"),
                        ],
                        max_length=20,
                        verbose_name="Источник",
                    ),
                ),
                ("url", models.TextField(blank=True, verbose_name="URL")),
                (
                    "proj_guid",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="GUID проекта ФИПИ"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="running", max_length=20, verbose_name="Статус"
                    ),
                ),
                (
                    "tasks_added",
                    models.PositiveIntegerField(default=0, verbose_name="Добавлено"),
                ),
                (
                    "tasks_skipped",
                    models.PositiveIntegerField(default=0, verbose_name="Пропущено"),
                ),
                (
                    "tasks_duplicate",
                    models.PositiveIntegerField(default=0, verbose_name="Дублей"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Заметки")),
            ],
            options={
                "verbose_name": "Сессия импорта",
                "verbose_name_plural": "Сессии импорта",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="catalogtask",
            name="fipi_guid",
            field=models.CharField(
                blank=True,
                max_length=64,
                null=True,
                unique=True,
                verbose_name="GUID ФИПИ",
            ),
        ),
        migrations.AddField(
            model_name="catalogtask",
            name="text_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=32,
                null=True,
                verbose_name="Хэш текста",
            ),
        ),
        migrations.AddField(
            model_name="catalogtask",
            name="import_session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="exam.catalogimportsession",
                verbose_name="Сессия импорта",
            ),
        ),
    ]
