# Generated by Django 6.0 on 2026-04-09 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0008_fipi_import"),
    ]

    operations = [
        migrations.AlterField(
            model_name="catalogtask",
            name="source",
            field=models.CharField(
                choices=[
                    ("fipi", "ФИПИ"),
                    ("sdamgia", "СдамГИА"),
                    ("print_solve", "Распечатай и реши"),
                    ("dinamika", "Динамика"),
                    ("manual", "Вручную"),
                ],
                default="manual",
                max_length=20,
                verbose_name="Источник",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="source",
            field=models.CharField(
                choices=[
                    ("fipi", "ФИПИ"),
                    ("sdamgia", "СдамГИА"),
                    ("print_solve", "Распечатай и реши"),
                    ("dinamika", "Динамика"),
                    ("manual", "Вручную"),
                ],
                default="manual",
                max_length=20,
                verbose_name="Источник",
            ),
        ),
    ]
