# Generated by Django 6.0 on 2026-04-10 17:16

from django.db import migrations, models

import exam.models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0009_alter_catalogtask_source_alter_task_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="catalogimportsession",
            name="source",
            field=models.CharField(
                choices=[
                    ("fipi", "ФИПИ"),
                    ("sdamgia", "СдамГИА"),
                    ("print_solve", "Распечатай и реши"),
                    ("dinamika", "Динамика"),
                    ("manual", "Вручную"),
                ],
                max_length=20,
                verbose_name="Источник",
            ),
        ),
        migrations.AlterField(
            model_name="catalogtask",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="catalog/",
                validators=[exam.models.validate_image_size],
                verbose_name="Изображение",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="tasks/",
                validators=[exam.models.validate_image_size],
                verbose_name="Изображение",
            ),
        ),
    ]
