# Generated by Django 6.0.3 on 2026-04-13 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exam", "0011_shared_context"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="awarded_points",
            field=models.IntegerField(blank=True, null=True, verbose_name="Начислено баллов"),
        ),
        migrations.AddField(
            model_name="catalogtask",
            name="no_student_input",
            field=models.BooleanField(
                default=False,
                help_text="Задание решается на бумаге — студент ничего не вводит (напр. ОГЭ 20–25)",
                verbose_name="Без поля ответа",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="no_student_input",
            field=models.BooleanField(
                default=False,
                help_text="Задание решается на бумаге — студент ничего не вводит (напр. ОГЭ 20–25)",
                verbose_name="Без поля ответа",
            ),
        ),
    ]
