# Generated by Django 6.0.3 on 2026-04-13 16:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("exam", "0012_no_student_input_awarded_points"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="catalogtask",
            name="topic",
        ),
        migrations.RemoveField(
            model_name="task",
            name="topic",
        ),
    ]
