# Generated by Django 6.0.3 on 2026-04-15 12:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exam", "0013_remove_topic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="full_name",
            field=models.CharField(max_length=255, verbose_name="ФИО"),
        ),
        migrations.AlterUniqueTogether(
            name="student",
            unique_together={("school_class", "full_name")},
        ),
    ]
