# Generated by Django 6.0.3 on 2026-04-15 12:45

import django.db.models.deletion
from django.db import migrations, models

import exam.models


class Migration(migrations.Migration):
    dependencies = [
        ("exam", "0014_student_unique_together_by_class"),
    ]

    operations = [
        migrations.CreateModel(
            name="CatalogTaskImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="catalog/",
                        validators=[exam.models.validate_image_size],
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extra_images",
                        to="exam.catalogtask",
                        verbose_name="Задание каталога",
                    ),
                ),
            ],
            options={
                "verbose_name": "Доп. изображение каталога",
                "verbose_name_plural": "Доп. изображения каталога",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="TaskImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="tasks/",
                        validators=[exam.models.validate_image_size],
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extra_images",
                        to="exam.task",
                        verbose_name="Задание",
                    ),
                ),
            ],
            options={
                "verbose_name": "Доп. изображение",
                "verbose_name_plural": "Доп. изображения",
                "ordering": ["order"],
            },
        ),
    ]
