# Generated by Django 5.2.3 on 2026-04-18 11:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exam", "0015_task_extra_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variant",
            name="number",
            field=models.CharField(max_length=100, unique=True, verbose_name="Номер варианта"),
        ),
    ]
