# Generated by Django 5.2.3 on 2026-04-25 08:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exam", "0016_variant_number_max_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="session_key",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=255,
                null=True,
                verbose_name="Ключ сессии",
            ),
        ),
    ]
