# Generated by Django 5.2.3 on 2026-05-06 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exam", "0017_alter_student_session_key"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="attempt",
            index=models.Index(fields=["student", "variant"], name="exam_attemp_student_02c4de_idx"),
        ),
    ]
